### ISSUE TITLE
Build can fail on Rust 1.94.0 with stale workspace Cargo.lock resolving spindle 0.2.5

### ISSUE THREAD

**Issue by terasakisatoshi** [SpM-lab/sparse-ir-rs#226]
# Build can fail on Rust 1.94.0 when a stale workspace lockfile resolves `spindle 0.2.5`

## Summary

The workspace can fail to build on `rustc 1.94.0` if the local workspace `Cargo.lock` resolves `spindle 0.2.5`.

The failure shows up before project code runs:

```text
error[E0597]: `task` does not live long enough
...
note: raw pointer casts of trait objects cannot extend lifetimes
...
= help: see <https://github.com/rust-lang/rust/issues/141402> for more information
```

The dependency path is:

```text
spindle -> faer -> sparse-ir
```

In my local reproduction, updating the resolution from `spindle 0.2.5` to `spindle 0.2.6` fixed the problem, and the following paths then passed on `rustc 1.94.0`:

- `cargo run -p sparse-ir --example roundtrip --release`
- `cargo build --release -p sparse-ir-capi`
- `cd python && uv sync --offline && uv run pytest tests/ -v`
- `cd fortran && ./test_with_rust_capi.sh`

## Reproduction steps

These steps are written to reproduce the failure that occurs with the stale `0.2.5` resolution.

1. Use Rust `1.94.0`.

   ```bash
   rustc --version
   # expected: rustc 1.94.0
   ```

2. Make sure the workspace lockfile resolves `spindle 0.2.5`.

   Example check:

   ```bash
   rg -n '^name = "spindle"$|^version = "0\\.2\\.5"$' Cargo.lock
   ```

3. From the workspace root, run:

   ```bash
   cargo run -p sparse-ir --example roundtrip --release
   ```

4. Observe the build fail while compiling `spindle` with `E0597`.

## Expected behavior

The workspace should build successfully on current stable Rust, including the documented Rust quick start and the language-binding setup paths.

## Actual behavior

Build fails in a transitive dependency before the example or bindings can run.

## Notes

- `cargo +1.93.0 build --release -p sparse-ir --example roundtrip` succeeded locally.
- Updating the stale resolution to `spindle 0.2.6` also succeeded on `rustc 1.94.0`.
- The workspace root currently relies on each local checkout’s generated `Cargo.lock`, so contributors can get different outcomes depending on when their local lockfile was last refreshed.

## Proposed fix

Track the workspace `Cargo.lock` in the repository so contributors share a known-good transitive dependency resolution, including `spindle 0.2.6`.
